### ISSUE TITLE
`cuprated` is buggy if STDIN pipe is not available

### ISSUE THREAD

**Issue by hinto-janai** [Cuprate/cuprate#396]
## Environment
All, [7d18098](https://github.com/Cuprate/cuprate/commit/7d18098b4ce17dea2bbd1f309bd36bcdd8f977a3).

## Bug
If STDIN is not available (e.g. docker/systemd setup), `cuprated` has buggy behavior.

## Expected behavior
Detection on when STDIN is not available.

## Steps to reproduce
1. Start `cuprated` as a normal systemd service or inside a docker container without STDIN
2. See buggy output (e.g. spamming of `help` message)

**Comment by sethforprivacy** [comment]
Note that you can workaround this and allow proper commands to be passed in the container by adding the following to a Docker Compose setup:

```yaml
    tty: true
    stdin_open: true
```

i.e.

```yaml
  cuprated:
    image: ghcr.io/hundehausen/cuprate-docker:latest
    container_name: cuprated
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - cuprated-data:/home/cuprate/.local/share/cuprate
      - ./Cuprated.toml:/home/cuprate/.config/cuprate/Cuprated.toml
    command: ["--config-file", "/home/cuprate/.config/cuprate/Cuprated.toml"]
```
