### ISSUE TITLE
Configure directories for data & cache

### ISSUE THREAD

**Issue by physics515** [Cuprate/cuprate#409]
## Feature
Add a key to the configuration file to set the location of the data and cache directories.

## Why
I only have a 1TB OS drive on my PC but I an 86TB RAID10 setup where I would like the blockchain to be stored. I often flash my OS drive about every 3 months to start over clean and it would suck to have to resync every time.

**Comment by Boog900** [comment]
The default config file generated does not generate all keys, we also are yet to document the full config in the user book.

You can change the paths by putting this in the config:

```toml
[fs]
data_directory = "path/to/folder"
cache_directory = "path/to/folder"
```

Hopefully that should work, I'll prioritize documenting the config for the user book.
